"""Initial migration

Revision ID: 31693476c3b2
Revises: 
Create Date: 2025-06-12 16:14:28.776070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31693476c3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_spent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_spent')

    # ### end Alembic commands ###
